export const laosProvinces = [
  { id: 'vt', name: 'Vientiane Prefecture', nameLo: 'ນະຄອນຫຼວງວຽງຈັນ' },
  { id: 'ps', name: 'Phongsaly', nameLo: 'ຜົ້ງສາລີ' },
  { id: 'ln', name: 'Luang Namtha', nameLo: 'ຫຼວງນໍ້າທາ' },
  { id: 'od', name: 'Oudomxay', nameLo: 'ອຸດົມໄຊ' },
  { id: 'bk', name: 'Bokeo', nameLo: 'ບໍ່ແກ້ວ' },
  { id: 'lp', name: 'Luang Prabang', nameLo: 'ຫຼວງພະບາງ' },
  { id: 'hp', name: 'Houaphanh', nameLo: 'ຫົວພັນ' },
  { id: 'xb', name: 'Xayaboury', nameLo: 'ໄຊຍະບູລີ' },
  { id: 'xk', name: 'Xieng Khouang', nameLo: 'ຊຽງຂວາງ' },
  { id: 'vp', name: 'Vientiane Province', nameLo: 'ແຂວງວຽງຈັນ' },
  { id: 'bx', name: 'Borikhamxay', nameLo: 'ບໍລິຄຳໄຊ' },
  { id: 'km', name: 'Khammouane', nameLo: 'ຄຳມ່ວນ' },
  { id: 'sk', name: 'Savannakhet', nameLo: 'ສະຫວັນນະເຂດ' },
  { id: 'sl', name: 'Salavan', nameLo: 'ສາລະວັນ' },
  { id: 'sg', name: 'Sekong', nameLo: 'ເຊກອງ' },
  { id: 'cp', name: 'Champasak', nameLo: 'ຈຳປາສັກ' },
  { id: 'at', name: 'Attapeu', nameLo: 'ອັດຕະປື' },
  { id: 'xs', name: 'Xaysomboun', nameLo: 'ໄຊສົມບູນ' },
];

export const laosDistricts: Record<string, { id: string, name: string, nameLo: string }[]> = {
  'vt': [
    { id: 'vt-1', name: 'Chanthabouly', nameLo: 'ຈັນທະບູລີ' },
    { id: 'vt-2', name: 'Sikhottabong', nameLo: 'ສີໂຄດຕະບອງ' },
    { id: 'vt-3', name: 'Xaysetha', nameLo: 'ໄຊເສດຖາ' },
    { id: 'vt-4', name: 'Sisattanak', nameLo: 'ສີສັດຕະນາກ' },
    { id: 'vt-5', name: 'Naxaithong', nameLo: 'ນາຊາຍທອງ' },
    { id: 'vt-6', name: 'Xaythany', nameLo: 'ໄຊທານີ' },
    { id: 'vt-7', name: 'Hadxaifong', nameLo: 'ຫາດຊາຍຟອງ' },
    { id: 'vt-8', name: 'Sangthong', nameLo: 'ສັງທອງ' },
    { id: 'vt-9', name: 'Mayparkngum', nameLo: 'ປາກງື່ມ' },
  ],
  'ps': [
    { id: 'ps-1', name: 'Phongsaly', nameLo: 'ຜົ້ງສາລີ' },
    { id: 'ps-2', name: 'May', nameLo: 'ໃໝ່' },
    { id: 'ps-3', name: 'Khoua', nameLo: 'ຂວາ' },
    { id: 'ps-4', name: 'Samphanh', nameLo: 'ສຳພັນ' },
    { id: 'ps-5', name: 'Boun Neua', nameLo: 'ບຸນເໜືອ' },
    { id: 'ps-6', name: 'Yot Ou', nameLo: 'ຍອດອູ' },
    { id: 'ps-7', name: 'Boun Tay', nameLo: 'ບຸນໃຕ້' },
  ],
  'ln': [
    { id: 'ln-1', name: 'Namtha', nameLo: 'ນໍ້າທາ' },
    { id: 'ln-2', name: 'Sing', nameLo: 'ສິງ' },
    { id: 'ln-3', name: 'Long', nameLo: 'ລອງ' },
    { id: 'ln-4', name: 'Viengphoukha', nameLo: 'ວຽງພູຄາ' },
    { id: 'ln-5', name: 'Na Le', nameLo: 'ນາແລ' },
  ],
  'od': [
    { id: 'od-1', name: 'Xay', nameLo: 'ໄຊ' },
    { id: 'od-2', name: 'La', nameLo: 'ຫຼ້າ' },
    { id: 'od-3', name: 'Namo', nameLo: 'ນາໝໍ້' },
    { id: 'od-4', name: 'Nga', nameLo: 'ງາ' },
    { id: 'od-5', name: 'Beng', nameLo: 'ແບ່ງ' },
    { id: 'od-6', name: 'Houn', nameLo: 'ຮຸນ' },
    { id: 'od-7', name: 'Pak Beng', nameLo: 'ປາກແບ່ງ' },
  ],
  'bk': [
    { id: 'bk-1', name: 'Houayxay', nameLo: 'ຫ້ວຍຊາຍ' },
    { id: 'bk-2', name: 'Tonpheung', nameLo: 'ຕົ້ນເຜິ້ງ' },
    { id: 'bk-3', name: 'Meung', nameLo: 'ເມິງ' },
    { id: 'bk-4', name: 'Pha Oudom', nameLo: 'ຜາອຸດົມ' },
    { id: 'bk-5', name: 'Paktha', nameLo: 'ປາກທາ' },
  ],
  'lp': [
    { id: 'lp-1', name: 'Luang Prabang', nameLo: 'ຫຼວງພະບາງ' },
    { id: 'lp-2', name: 'Xiengngeun', nameLo: 'ຊຽງເງິນ' },
    { id: 'lp-3', name: 'Nane', nameLo: 'ນານ' },
    { id: 'lp-4', name: 'Pak Ou', nameLo: 'ປາກອູ' },
    { id: 'lp-5', name: 'Nambak', nameLo: 'ນ້ຳບາກ' },
    { id: 'lp-6', name: 'Ngoy', nameLo: 'ງອຍ' },
    { id: 'lp-7', name: 'Pak Seng', nameLo: 'ປາກແຊງ' },
    { id: 'lp-8', name: 'Phonxay', nameLo: 'ໂພນໄຊ' },
    { id: 'lp-9', name: 'Chomphet', nameLo: 'ຈອມເພັດ' },
    { id: 'lp-10', name: 'Viengkham', nameLo: 'ວຽງຄຳ' },
    { id: 'lp-11', name: 'Phoukhoune', nameLo: 'ພູຄູນ' },
    { id: 'lp-12', name: 'Phonthong', nameLo: 'ໂພນທອງ' },
  ],
  'hp': [
    { id: 'hp-1', name: 'Xamneua', nameLo: 'ຊຳເໜືອ' },
    { id: 'hp-2', name: 'Xiengkhor', nameLo: 'ຊຽງຄໍ້' },
    { id: 'hp-3', name: 'Viengthong', nameLo: 'ວຽງທອງ' },
    { id: 'hp-4', name: 'Viengxay', nameLo: 'ວຽງໄຊ' },
    { id: 'hp-5', name: 'Houameuang', nameLo: 'ຫົວເມືອງ' },
    { id: 'hp-6', name: 'Samtay', nameLo: 'ຊຳໃຕ້' },
    { id: 'hp-7', name: 'Sop Bao', nameLo: 'ສົບເບົາ' },
    { id: 'hp-8', name: 'Et', nameLo: 'ແອດ' },
  ],
  'xb': [
    { id: 'xb-1', name: 'Xayaboury', nameLo: 'ໄຊຍະບູລີ' },
    { id: 'xb-2', name: 'Khop', nameLo: 'ຄອບ' },
    { id: 'xb-3', name: 'Hongsa', nameLo: 'ຫົງສາ' },
    { id: 'xb-4', name: 'Ngeun', nameLo: 'ເງິນ' },
    { id: 'xb-5', name: 'Xienghone', nameLo: 'ຊຽງຮ່ອນ' },
    { id: 'xb-6', name: 'Phiang', nameLo: 'ພຽງ' },
    { id: 'xb-7', name: 'Parklai', nameLo: 'ປາກລາຍ' },
    { id: 'xb-8', name: 'Kenethao', nameLo: 'ແກ່ນທ້າວ' },
    { id: 'xb-9', name: 'Botene', nameLo: 'ບໍ່ແຕນ' },
    { id: 'xb-10', name: 'Thongmyxay', nameLo: 'ທົ່ງມີໄຊ' },
    { id: 'xb-11', name: 'Xaisathan', nameLo: 'ໄຊສະຖານ' },
  ],
  'xk': [
    { id: 'xk-1', name: 'Pek', nameLo: 'ແປກ' },
    { id: 'xk-2', name: 'Kham', nameLo: 'ຄຳ' },
    { id: 'xk-3', name: 'Nong Het', nameLo: 'ໜອງແຮດ' },
    { id: 'xk-4', name: 'Khoune', nameLo: 'ຄູນ' },
    { id: 'xk-5', name: 'Mork May', nameLo: 'ໝອກໃໝ່' },
    { id: 'xk-6', name: 'Phou Kout', nameLo: 'ພູກູດ' },
    { id: 'xk-7', name: 'Phaxay', nameLo: 'ຜາໄຊ' },
  ],
  'vp': [
    { id: 'vp-1', name: 'Phonhong', nameLo: 'ໂພນໂຮງ' },
    { id: 'vp-2', name: 'Thoulakhom', nameLo: 'ທຸລະຄົມ' },
    { id: 'vp-3', name: 'Keo Oudom', nameLo: 'ແກ້ວອຸດົມ' },
    { id: 'vp-4', name: 'Kasy', nameLo: 'ກາສີ' },
    { id: 'vp-5', name: 'Vang Vieng', nameLo: 'ວັງວຽງ' },
    { id: 'vp-6', name: 'Feuang', nameLo: 'ເຟືອງ' },
    { id: 'vp-7', name: 'Xanakharm', nameLo: 'ຊະນະຄາມ' },
    { id: 'vp-8', name: 'Mad', nameLo: 'ແມດ' },
    { id: 'vp-9', name: 'Viengkham', nameLo: 'ວຽງຄຳ' },
    { id: 'vp-10', name: 'Hinhirp', nameLo: 'ຫີນເຫີບ' },
  ],
  'bx': [
    { id: 'bx-1', name: 'Paksan', nameLo: 'ປາກຊັນ' },
    { id: 'bx-2', name: 'Thaphabat', nameLo: 'ທ່າພະບາດ' },
    { id: 'bx-3', name: 'Pakkading', nameLo: 'ປາກກະດິງ' },
    { id: 'bx-4', name: 'Borikhane', nameLo: 'ບໍລິຄັນ' },
    { id: 'bx-5', name: 'Khamkeut', nameLo: 'ຄຳເກີດ' },
    { id: 'bx-6', name: 'Viengthong', nameLo: 'ວຽງທອງ' },
    { id: 'bx-7', name: 'Xaychamphone', nameLo: 'ໄຊຈຳພອນ' },
  ],
  'km': [
    { id: 'km-1', name: 'Thakhek', nameLo: 'ທ່າແຂກ' },
    { id: 'km-2', name: 'Mahaxay', nameLo: 'ມະຫາໄຊ' },
    { id: 'km-3', name: 'Nong Bok', nameLo: 'ໜອງບົກ' },
    { id: 'km-4', name: 'Hingboun', nameLo: 'ຫີນບູນ' },
    { id: 'km-5', name: 'Nhommalath', nameLo: 'ຍົມມະລາດ' },
    { id: 'km-6', name: 'Bualapha', nameLo: 'ບົວລະພາ' },
    { id: 'km-7', name: 'Nakai', nameLo: 'ນາກາຍ' },
    { id: 'km-8', name: 'Sebangfai', nameLo: 'ເຊບັ້ງໄຟ' },
    { id: 'km-9', name: 'Xaybouathong', nameLo: 'ໄຊບົວທອງ' },
    { id: 'km-10', name: 'Kounkham', nameLo: 'ຄູນຄຳ' },
  ],
  'sk': [
    { id: 'sk-1', name: 'Kaysone Phomvihane', nameLo: 'ໄກສອນ ພົມວິຫານ' },
    { id: 'sk-2', name: 'Outhoumphone', nameLo: 'ອຸທຸມພອນ' },
    { id: 'sk-3', name: 'Atsaphangthong', nameLo: 'ອາດສະພັງທອງ' },
    { id: 'sk-4', name: 'Phine', nameLo: 'ພີນ' },
    { id: 'sk-5', name: 'Sepon', nameLo: 'ເຊໂປນ' },
    { id: 'sk-6', name: 'Nong', nameLo: 'ນອງ' },
    { id: 'sk-7', name: 'Thapangthong', nameLo: 'ທ່າປາງທອງ' },
    { id: 'sk-8', name: 'Songkhone', nameLo: 'ສອງຄອນ' },
    { id: 'sk-9', name: 'Champhone', nameLo: 'ຈຳພອນ' },
    { id: 'sk-10', name: 'Xonbouri', nameLo: 'ຊົນບູລີ' },
    { id: 'sk-11', name: 'Xaybouri', nameLo: 'ໄຊບູລີ' },
    { id: 'sk-12', name: 'Vilabouri', nameLo: 'ວີລະບູລີ' },
    { id: 'sk-13', name: 'Atsaphone', nameLo: 'ອາດສະພອນ' },
    { id: 'sk-14', name: 'Xayphouthong', nameLo: 'ໄຊພູທອງ' },
    { id: 'sk-15', name: 'Phalanxay', nameLo: 'ພະລານໄຊ' },
  ],
  'sl': [
    { id: 'sl-1', name: 'Salavan', nameLo: 'ສາລະວັນ' },
    { id: 'sl-2', name: 'Ta Oi', nameLo: 'ຕະໂອ້ຍ' },
    { id: 'sl-3', name: 'Toomlan', nameLo: 'ຕຸ້ມລານ' },
    { id: 'sl-4', name: 'Lakhonepheng', nameLo: 'ລະຄອນເພັງ' },
    { id: 'sl-5', name: 'Vapi', nameLo: 'ວາປີ' },
    { id: 'sl-6', name: 'Khongxedon', nameLo: 'ຄົງເຊໂດນ' },
    { id: 'sl-7', name: 'Lao Ngam', nameLo: 'ເລົ່າງາມ' },
    { id: 'sl-8', name: 'Samuoi', nameLo: 'ສະໝ້ວຍ' },
  ],
  'sg': [
    { id: 'sg-1', name: 'Lamarm', nameLo: 'ລະມາມ' },
    { id: 'sg-2', name: 'Kaleum', nameLo: 'ກະເລິມ' },
    { id: 'sg-3', name: 'Dakcheung', nameLo: 'ດັກຈຶງ' },
    { id: 'sg-4', name: 'Thateng', nameLo: 'ທ່າແຕງ' },
  ],
  'cp': [
    { id: 'cp-1', name: 'Pakse', nameLo: 'ປາກເຊ' },
    { id: 'cp-2', name: 'Sanasomboun', nameLo: 'ຊະນະສົມບູນ' },
    { id: 'cp-3', name: 'Bachiangchaleunsook', nameLo: 'ບາຈຽງຈະເລີນສຸກ' },
    { id: 'cp-4', name: 'Paksong', nameLo: 'ປາກຊ່ອງ' },
    { id: 'cp-5', name: 'Pathouphone', nameLo: 'ປະທຸມພອນ' },
    { id: 'cp-6', name: 'Phonthong', nameLo: 'ໂພນທອງ' },
    { id: 'cp-7', name: 'Champassack', nameLo: 'ຈຳປາສັກ' },
    { id: 'cp-8', name: 'Soukhoumma', nameLo: 'ສຸຂຸມາ' },
    { id: 'cp-9', name: 'Mounlapamok', nameLo: 'ມູນລະປະໂມກ' },
    { id: 'cp-10', name: 'Khong', nameLo: 'ໂຂງ' },
  ],
  'at': [
    { id: 'at-1', name: 'Xaysetha', nameLo: 'ໄຊເສດຖາ' },
    { id: 'at-2', name: 'Samakhixay', nameLo: 'ສາມັກຄີໄຊ' },
    { id: 'at-3', name: 'Sanamxay', nameLo: 'ສະໜາມໄຊ' },
    { id: 'at-4', name: 'Phouvong', nameLo: 'ພູວົງ' },
    { id: 'at-5', name: 'Xanxay', nameLo: 'ຊານໄຊ' },
  ],
  'xs': [
    { id: 'xs-1', name: 'Anouvong', nameLo: 'ອະນຸວົງ' },
    { id: 'xs-2', name: 'Longchaeng', nameLo: 'ລ້ອງແຈ້ງ' },
    { id: 'xs-3', name: 'Thathom', nameLo: 'ທ່າໂທມ' },
    { id: 'xs-4', name: 'Longxan', nameLo: 'ລ້ອງຊານ' },
    { id: 'xs-5', name: 'Hom', nameLo: 'ຮົ່ມ' },
  ],
};

export const getDistrictsForProvince = (provinceId: string) => {
  return laosDistricts[provinceId] || [];
};
